name: PR Vitest Tests

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - master

env:
  WORKING_DIRECTORY: 100-days-of-code-ts

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      challenges: ${{ steps.filter.outputs.challenges }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for changes in challenges directory
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            challenges:
              - '${{ env.WORKING_DIRECTORY }}/src/challenges/**'
              - '${{ env.WORKING_DIRECTORY }}/package.json'
              - '${{ env.WORKING_DIRECTORY }}/package-lock.json'
              - '${{ env.WORKING_DIRECTORY }}/tsconfig.json'
              - '${{ env.WORKING_DIRECTORY }}/vitest.config.ts'
  test:
    name: Run test codes
    if: |
      github.event.pull_request.draft == false 
      &&  !startsWith(github.head_ref, 'release')
      &&  !startsWith(github.head_ref, 'doc')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ env.WORKING_DIRECTORY }}/package.json
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run Vitest
        run: npx vitest run --coverage

      - name: Show coverage
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}
